ease_home owl file is added
ease-crc/soma pull request #126
Opened 2020-09-08 11:04 UTC by AbhijitVyas

2020-09-08 11:05 UTC, AbhijitVyas commented
As discussed in last OTF meeting, ease_home is moved to SOMA repository as of now.

2020-09-09 18:53 UTC, daniel86 commented
> As discussed in last OTF meeting, ease_home is moved to SOMA repository as of now.

Please name the file "SOMA-HOME.owl"

2020-09-09 18:59 UTC, daniel86 requested changes

2020-09-09 18:59 UTC, daniel86 commented on owl/ease_home.owl
> +    <owl:Ontology rdf:about="http://www.ease-crc.org/ont/ease-home.owl"/>
- import of SOMA.owl is missing
- a small description would be nice (annotation property)
- the name should be rather "SOMA-HOME"

2020-09-15 08:50 UTC, daniel86 requested changes

2020-09-15 08:50 UTC, daniel86 commented on owl/SOMA-HOME.owl
> +<rdf:RDF xmlns="http://www.ease-crc.org/ont/ease-home.owl#"
here is still ease-home, please change to SOMA-HOME.owl

2020-09-15 08:50 UTC, daniel86 commented on owl/SOMA-HOME.owl
> +        <rdfs:comment>SOMA-HOME concentrates on the concepts that are specific to home, e.g. kitchen environment, household stuff.</rdfs:comment>
better: SOMA-HOME defines ...

2020-09-15 08:50 UTC, daniel86 commented on owl/SOMA-HOME.owl
> +        <rdfs:comment>SOMA-HOME concentrates on the concepts that are specific to home, e.g. kitchen environment, household stuff.</rdfs:comment>
better: household items

2020-09-15 08:50 UTC, daniel86 commented on owl/SOMA-HOME.owl
> +        <rdfs:comment>todo(DB): this seems too specific. Should it go to a more specific ontology? like &quot;SOMA-kitchen&quot;?</rdfs:comment>
this todo can be removed now

2020-09-15 08:50 UTC, daniel86 commented on owl/SOMA-HOME.owl
> +        <rdfs:comment>todo(DB): this seems too specific. Should it go to a more specific ontology? like &quot;SOMA-kitchen&quot;?</rdfs:comment>
the todo can be removed now

2020-09-15 08:50 UTC, daniel86 commented on owl/SOMA-HOME.owl
> +        <rdfs:comment>todo(DB): this seems too specific. Should it go to a more specific ontology? like &quot;SOMA-kitchen&quot;?</rdfs:comment>
the todo can be removed

2020-09-17 12:53 UTC, mpomarlan commented
I have nothing to add to what Daniel said, so I didn't open a review.

2020-09-20 11:56 UTC, daniel86 requested changes

2020-09-20 11:56 UTC, daniel86 commented on owl/SOMA-HOME.owl
> +<rdf:RDF xmlns="http://www.ease-crc.org/ont/soma-home.owl#"
better use uppercase latter, not sure if it matters or not.
so use *SOMA-HOME.owl* exactly as I wrote it here.

2020-09-20 11:58 UTC, daniel86 commented
@AbhijitVyas merge with master to get rid of error in OOPS, I think their servers are offline at the moment

2020-09-20 12:30 UTC, daniel86 approved these changes

2020-09-20 12:30 UTC, merged