SOMA-Agent
ease-crc/soma pull request #297
Opened 2023-02-13 15:52 UTC by mrnolte

Introduced the pattern to model preferences

2023-02-14 11:17 UTC, mpomarlan commented
Oof how are the diffs always this big? And a lot of the differences are trivial but distracting (blablawholeprefix becomes soma and such).

(And might be nice to have SOMA-Agent in functional notation).

2023-02-14 15:16 UTC, mrnolte commented
The differences should be minimal after the merge of #286, as this branch is based on that.

2023-02-14 15:18 UTC, mrnolte commented
I now saved SOMA-AGENT as functional Syntax.

2023-08-04 13:38 UTC, mpomarlan requested changes
See comments.

I notice there is a ton of stuff in SOMA.owl. It should not be there, but I think we talked about this previously, and it will be repositioned in some future PR.

2023-08-04 13:38 UTC, mpomarlan commented on owl/SOMA-OBJ.owl
> +AnnotationAssertion(rdfs:comment SOMA:PerformerRole "A role classifying an Agent responsible for performing an Action.
It seems this annotation needs an update to reflect the renaming AgentRole -> PerformerRole.

2023-08-04 13:38 UTC, mpomarlan commented on owl/SOMA.owl
> +SubObjectPropertyOf(SOMA:isSourceFor <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#associatedWith>)
Should this have domain and range set to InformationObject?

2023-09-24 11:22 UTC, ayden175 commented on owl/SOMA-ACT.owl
> +ObjectPropertyDomain(SOMA:hasAnswer SOMA:Answer)
Maybe Agent would make more sense for the domain, unless there is another more fitting class?

2023-09-25 10:37 UTC, mrnolte commented on owl/SOMA-ACT.owl
> +SubClassOf(SOMA:Imagining SOMA:InformationAcquisition)
Going by the Definition of InformationAcquisition, which is that an Agent acquires new Information, i.e., there is an output role Knowledge, and that Imagining constructs a mental representation of some (possibly future) state, which then would be the output, I sorted it here. Where would you put it instead?

2023-09-25 10:39 UTC, mrnolte commented on owl/SOMA-ACT.owl
> +ObjectPropertyDomain(SOMA:hasAnswer SOMA:Answer)
Was an error, fixed it. Should be Message.

2023-09-25 10:39 UTC, mrnolte commented on owl/SOMA-ACT.owl
> +ObjectPropertyRange(SOMA:answers SOMA:Message)
This was an error, answers has as domain answer and as range message, and the inverse is true for hasAnswer. Fixed it.

2023-09-25 10:39 UTC, mrnolte commented on owl/SOMA-ACT.owl
> +SubObjectPropertyOf(ObjectPropertyChain(<http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#includesEvent> SOMA:hasInitialSituation SOMA:hasTerminalSituation <http://www.ontologydesignpatterns.org
Fixed it

2023-10-05 09:30 UTC, merged